p8105\_hw2\_aar2192
================
Amadeia Rector
10/05/2018

Problem 1
=========

### **Reading** and **cleaning** the data

``` r
nyc_transit =
  read_csv(file = "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names() %>% 
  select(line, station_name:entry,vending, ada) %>% 
  mutate(entry = recode(entry,"YES" = TRUE, "NO" = FALSE))
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_integer(),
    ##   Route9 = col_integer(),
    ##   Route10 = col_integer(),
    ##   Route11 = col_integer(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

### Describing the Data

``` r
nyc_transit
```

    ## # A tibble: 1,868 x 19
    ##    line  station_name station_latitude station_longitu… route1 route2
    ##    <chr> <chr>                   <dbl>            <dbl> <chr>  <chr> 
    ##  1 4 Av… 25th St                  40.7            -74.0 R      <NA>  
    ##  2 4 Av… 25th St                  40.7            -74.0 R      <NA>  
    ##  3 4 Av… 36th St                  40.7            -74.0 N      R     
    ##  4 4 Av… 36th St                  40.7            -74.0 N      R     
    ##  5 4 Av… 36th St                  40.7            -74.0 N      R     
    ##  6 4 Av… 45th St                  40.6            -74.0 R      <NA>  
    ##  7 4 Av… 45th St                  40.6            -74.0 R      <NA>  
    ##  8 4 Av… 45th St                  40.6            -74.0 R      <NA>  
    ##  9 4 Av… 45th St                  40.6            -74.0 R      <NA>  
    ## 10 4 Av… 53rd St                  40.6            -74.0 R      <NA>  
    ## # ... with 1,858 more rows, and 13 more variables: route3 <chr>,
    ## #   route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>, route8 <int>,
    ## #   route9 <int>, route10 <int>, route11 <int>, entrance_type <chr>,
    ## #   entry <lgl>, vending <chr>, ada <lgl>

``` r
str(nyc_transit)
```

    ## Classes 'tbl_df', 'tbl' and 'data.frame':    1868 obs. of  19 variables:
    ##  $ line             : chr  "4 Avenue" "4 Avenue" "4 Avenue" "4 Avenue" ...
    ##  $ station_name     : chr  "25th St" "25th St" "36th St" "36th St" ...
    ##  $ station_latitude : num  40.7 40.7 40.7 40.7 40.7 ...
    ##  $ station_longitude: num  -74 -74 -74 -74 -74 ...
    ##  $ route1           : chr  "R" "R" "N" "N" ...
    ##  $ route2           : chr  NA NA "R" "R" ...
    ##  $ route3           : chr  NA NA NA NA ...
    ##  $ route4           : chr  NA NA NA NA ...
    ##  $ route5           : chr  NA NA NA NA ...
    ##  $ route6           : chr  NA NA NA NA ...
    ##  $ route7           : chr  NA NA NA NA ...
    ##  $ route8           : int  NA NA NA NA NA NA NA NA NA NA ...
    ##  $ route9           : int  NA NA NA NA NA NA NA NA NA NA ...
    ##  $ route10          : int  NA NA NA NA NA NA NA NA NA NA ...
    ##  $ route11          : int  NA NA NA NA NA NA NA NA NA NA ...
    ##  $ entrance_type    : chr  "Stair" "Stair" "Stair" "Stair" ...
    ##  $ entry            : logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
    ##  $ vending          : chr  "YES" "YES" "YES" "YES" ...
    ##  $ ada              : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...

The dataset contains **1868 observations** and **19 variables**: line, station\_name, station\_latitude, station\_longitude, route1, route2, route3, route4, route5, route6, route7, route8, route9, route10, route11, entrance\_type, entry, vending, ada. The variable types are **character**, **integer**, and **logical**.

The data were first cleaned removing spaces between words that were then instead turned into underscores to join words, and letters were decapitalized. Then, certain variables were retained and one variable, *entry*, was recategorized as logical. As mentioned previously, the **dimensions** of the dataset are **1,868 X 19**.

The data do ***not*** appear to be tidy as certain columns, for example route1-route11 are values rather than separate variables and thus should be regrouped in a tidier format.

### Answering questions

The following are questions regarding the nature of this dataset.

#### How many distinct stations are there?

``` r
nyc_transit %>% 
  distinct(station_name)
```

    ## # A tibble: 356 x 1
    ##    station_name            
    ##    <chr>                   
    ##  1 25th St                 
    ##  2 36th St                 
    ##  3 45th St                 
    ##  4 53rd St                 
    ##  5 59th St                 
    ##  6 77th St                 
    ##  7 86th St                 
    ##  8 95th St                 
    ##  9 9th St                  
    ## 10 Atlantic Av-Barclays Ctr
    ## # ... with 346 more rows

There are 356 unique station names.

#### How many stations are ADA compliant?

``` r
summary(nyc_transit$ada==TRUE)
```

    ##    Mode   FALSE    TRUE 
    ## logical    1400     468

There are 468 ADA compliant stations.

#### What proportion of station entrances/exits without vending allow entrance?

``` r
entry_no_vend_table = table(nyc_transit$entry, nyc_transit$vending)
prop_entry_no_vend = prop.table(entry_no_vend_table,2)
prop_entry_no_vend
```

    ##        
    ##                   NO          YES
    ##   FALSE 0.6229508197 0.0005934718
    ##   TRUE  0.3770491803 0.9994065282

The proportion of station entrances/exits without vending that allow entrance is 37.7%.

### Reformating the data

#### Making route number and route name separate variables

``` r
nyc_transit_tidy=nyc_transit %>% 
  gather(key =route_number, value =route_name, route1:route11) %>% 
  separate("route_number", into = c("remove", "route_number"), sep = 5) %>% 
  select(-"remove") %>% 
  na.omit()  
  str(nyc_transit_tidy)
```

    ## Classes 'tbl_df', 'tbl' and 'data.frame':    4270 obs. of  10 variables:
    ##  $ line             : chr  "4 Avenue" "4 Avenue" "4 Avenue" "4 Avenue" ...
    ##  $ station_name     : chr  "25th St" "25th St" "36th St" "36th St" ...
    ##  $ station_latitude : num  40.7 40.7 40.7 40.7 40.7 ...
    ##  $ station_longitude: num  -74 -74 -74 -74 -74 ...
    ##  $ entrance_type    : chr  "Stair" "Stair" "Stair" "Stair" ...
    ##  $ entry            : logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
    ##  $ vending          : chr  "YES" "YES" "YES" "YES" ...
    ##  $ ada              : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
    ##  $ route_number     : chr  "1" "1" "1" "1" ...
    ##  $ route_name       : chr  "R" "R" "N" "N" ...
    ##  - attr(*, "na.action")= 'omit' Named int  1869 1870 1874 1875 1876 1877 1878 1879 1880 1881 ...
    ##   ..- attr(*, "names")= chr  "1869" "1870" "1874" "1875" ...

#### How many distinct stations serve the A train?

``` r
just_A = nyc_transit_tidy %>% 
  filter(route_name =="A") 

length(unique(just_A$station_name))
```

    ## [1] 56

There are 56 distinct stations that serve the A train.

#### How many ADA complaint stations does the A train serve?

``` r
ada_A = just_A %>%
  filter(ada == TRUE)
length(unique(ada_A$station_name))
```

    ## [1] 16

There are 16 stations that serve the A that are ADA compliant.

Problem 2
=========

### Read and clean Mr. Trash Wheel sheet

``` r
mr_trash_dataset =
  readxl::read_excel("./data/HealthyHarborWaterWheelTotals2017-3.xlsx",
                     sheet = "Mr. Trash Wheel", range = "A2:N213") %>% 
  janitor::clean_names() %>% 
  filter(!is.na(dumpster)) %>% 
  mutate(sports_balls = as.integer(sports_balls))
```

### Read and clean precipitation data for 2016 and 2017

``` r
precipitation_2016 =
  readxl::read_excel("./data/HealthyHarborWaterWheelTotals2017-3.xlsx",
                     sheet = "2016 Precipitation", range = "A2:B15") %>% 
  janitor::clean_names() %>% 
  na.omit() %>% 
  mutate(year=2016) %>% 
  rename(total_precip = total)
```

``` r
precipitation_2017 =
  readxl::read_excel("./data/HealthyHarborWaterWheelTotals2017-3.xlsx",
                     sheet = "2017 Precipitation",range = "A2:B15") %>% 
  janitor::clean_names() %>% 
  na.omit() %>% 
  mutate(year=2017) %>% 
  rename(total_precip = total)
View(precipitation_2017)
```
